In [1]:
import os
import sys
import torch as t
import pandas as pd
import numpy as np

PROJECT_ROOT = r"C:\Mestrado\Graph_Pruning\AnyGraph"

os.chdir(PROJECT_ROOT)
sys.path.insert(0, PROJECT_ROOT)
sys.argv = ["analysis"]

In [2]:
from node_classification.model import AnyGraph
from node_classification.params import args
import numpy as np
import warnings
import Utils.TimeLogger as logger

In [3]:
from Pruning_Methods.globalmagnitudepruner import GlobalMagnitudePruner

In [5]:
def load_model_from_checkpoint(checkpoint_path):
    #Configuração mínima que o model.py espera
    args.devices = ["cuda:0", "cuda:0"]

    #Carregando o modelo
    checkpoint = t.load(f"Models/{checkpoint_path}.mod", weights_only=False)
    model = checkpoint["model"]
    return model

In [6]:
model1 = load_model_from_checkpoint("pretrain_link1")
print(type(model1))

<class 'model.AnyGraph'>

In [7]:
pruner = GlobalMagnitudePruner(model1)

In [8]:
pruner.prune(0.30)
pruner.sparsity_report()

Threshold = 0.005317

{'Total': 16777216,
 'Zero': 5033166,
 'Remaining': 11744050,
 'Sparsity (%)': 30.000007152557373}

In [9]:
pruner.expert_report()

   Expert  Weights   Zeros  Sparsity (%)
0       0  2097152  876902     41.813946
1       1  2097152  455132     21.702385
2       2  2097152  888585     42.371035
3       3  2097152  659056     31.426239
4       4  2097152  339115     16.170263
5       5  2097152  548595     26.159048
6       6  2097152  398099     18.982840
7       7  2097152  867682     41.374302

In [19]:
df=pruner.layer_report()
df.head(10)

   Expert  Layer  Weights   Zeros  Sparsity (%)
0       0      0   262144   55201     21.057510
1       0      1   262144   38750     14.781952
2       0      2   262144   35985     13.727188
3       0      3   262144   65345     24.927139
4       0      4   262144  121914     46.506500
5       0      5   262144  161940     61.775208
6       0      6   262144  188354     71.851349
7       0      7   262144  209413     79.884720
8       1      0   262144   38978     14.868927
9       1      1   262144   35930     13.706207

In [11]:
pruner.remaining_statistics()

{'Remaining': 11744050,
 'Mean': 0.0011399935465306044,
 'Std': 0.03000212460756302,
 'Median': 0.006070356350392103,
 'Min': -0.6176326870918274,
 'Max': 0.6792733073234558}

In [4]:
from node_classification.data_handler import MultiDataHandler
from node_classification.main import Exp

In [5]:
datasets = {
    "node": [
        "cora",
        "arxiv",
        "pubmed",
        "home",
        "tech"
    ]
}

trn_datasets = datasets["node"]
tst_datasets = datasets["node"]

In [6]:
# Igual ao main.py
t.sparse.check_sparse_tensor_invariants.disable()

warnings.filterwarnings(
    "ignore",
    category=RuntimeWarning,
    message="divide by zero encountered in power"
)

os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu

if len(args.gpu.split(",")) == 2:
    args.devices = ["cuda:0", "cuda:1"]
elif len(args.gpu.split(",")) > 2:
    raise Exception("Devices should be less than 2")
else:
    args.devices = ["cuda:0", "cuda:0"]

logger.saveDefault = True

print(args)
print("Devices:", args.devices)

Namespace(lr=0.0001, batch=4096, tst_batch=256, epoch=100, save_path='tem', load_model=None, data='ml1m', tst_epoch=1, gpu='0', topk=20, epoch_max_step=-1, trn_mode='train-all', tst_mode='tst', eval_loss=True, ratio_fewshot_set=0.5, shot=5, tst_steps=-1, reg=1e-07, latdim=512, gnn_layer=3, fc_layer=8, gt_layer=2, head=4, anchor=256, act='relu', dataset_setting='training', assignment='top1', scale_layer=10, leaky=0.5, drop_rate=0.1, reca_range=0.2, selfloop=0, niter=2, expert_num=8, loss='ce', proj_method='both', nn='mlp', proj_trn_steps=100, attempt_cache=10000000, devices=['cuda:0', 'cuda:0'])
Devices: ['cuda:0', 'cuda:0']

In [7]:
handler = MultiDataHandler(
    trn_datasets,
    [tst_datasets]
)

2026-08-12 21:46:17.335444: Loading dataset arxiv
Dataset: arxiv, Node num: 169383, Edge num: 1456326
2026-08-12 21:46:22.246547: Loading dataset cora
Dataset: cora, Node num: 25191, Edge num: 121912
2026-08-12 21:46:22.709474: Loading dataset home
Dataset: home, Node num: 9795, Edge num: 149463
2026-08-12 21:46:23.008325: Loading dataset pubmed
Dataset: pubmed, Node num: 19720, Edge num: 124138
2026-08-12 21:46:23.311176: Loading dataset tech
Dataset: tech, Node num: 47431, Edge num: 2162611

Baseline

In [8]:
checkpoint="pretrain_link1"

exp = Exp(handler)

exp.prepare_model()

exp.load_model(checkpoint)

df = exp.evaluate()

print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-10 17:03:01.387425: Loaded pretrain_link1
2026-08-10 17:03:22.852121: Epoch 100/100, arxiv Test: Acc_mean = 0.4998, Acc_std = 0.0244, F1_mean = 0.3032, F1_std = 0.0096, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-10 17:03:25.731794: Epoch 100/100, cora Test: Acc_mean = 0.6185, Acc_std = 0.0088, F1_mean = 0.5621, F1_std = 0.0063, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-10 17:03:27.321507: Epoch 100/100, home Test: Acc_mean = 0.6678, Acc_std = 0.0407, F1_mean = 0.4327, F1_std = 0.0744, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-10 17:03:29.460876: Epoch 100/100, pubmed Test: Acc_mean = 0.6921, Acc_std = 0.0699, F1_mean = 0.6435, F1_std = 0.0770, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-10 17:06:20.220657: Epoch 100/100, tech Test: Acc_mean = 0.9583, Acc_std = 0.0118, F1_mean = 0.9134, F1_std = 0.0164, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-10 17:06:20.220657: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5865, Acc_std = 0.0190, F1_mean = 0.4259, F1_std = 0.0116
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.499825  0.024445  0.303197  0.009572      48603.0         0.0
1     cora  0.618512  0.008806  0.562120  0.006272       3414.0         0.0
2     home  0.667824  0.040672  0.432729  0.074422       1958.0         0.0
3   pubmed  0.692089  0.069858  0.643544  0.076998       3944.0         0.0
4     tech  0.958339  0.011823  0.913407  0.016356       9486.0         0.0
5  OVERALL  0.586494  0.019027  0.425864  0.011639          NaN         NaN

Pruning 90% link1

In [15]:
checkpoint="pretrain_link1"

exp = Exp(handler)

exp.prepare_model()

exp.load_model(checkpoint)

# Modelo pré-treinado
model_original = exp.model

# Cria uma cópia e poda essa cópia
pruner_mine = GlobalMagnitudePruner(model_original)

# Modelo novo, explicitamente podado
model_pruned = pruner_mine.prune(0.90)

# Passa explicitamente o modelo podado para o Exp
exp.model = model_pruned

# Confirma
print(pruner_mine.sparsity_report())

# Avalia o modelo PODADO
df = exp.evaluate()

print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 16:08:24.181141: Loaded pretrain_link1
Global Pruning: 90.0%
Threshold: 0.04173007
{'Threshold': 0.04173006862401962, 'Requested Sparsity (%)': 90.0, 'Total': 16777216, 'Zero': 15099494, 'Remaining': 1677722, 'Sparsity (%)': 89.99999761581421}
2026-08-12 16:08:49.757560: Epoch 100/100, arxiv Test: Acc_mean = 0.4797, Acc_std = 0.1136, F1_mean = 0.3469, F1_std = 0.0646, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 16:08:53.538686: Epoch 100/100, cora Test: Acc_mean = 0.5677, Acc_std = 0.0085, F1_mean = 0.5157, F1_std = 0.0151, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 16:08:55.793997: Epoch 100/100, home Test: Acc_mean = 0.5860, Acc_std = 0.0564, F1_mean = 0.3572, F1_std = 0.0691, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 16:08:58.544963: Epoch 100/100, pubmed Test: Acc_mean = 0.7401, Acc_std = 0.0464, F1_mean = 0.7232, F1_std = 0.0392, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 16:11:09.916199: Epoch 100/100, tech Test: Acc_mean = 0.9204, Acc_std = 0.0394, F1_mean = 0.7832, F1_std = 0.1270, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 16:11:09.917435: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5645, Acc_std = 0.0758, F1_mean = 0.4392, F1_std = 0.0370
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.479728  0.113643  0.346890  0.064564      48603.0         0.0
1     cora  0.567663  0.008538  0.515729  0.015120       3414.0         0.0
2     home  0.586006  0.056410  0.357173  0.069088       1958.0         0.0
3   pubmed  0.740061  0.046433  0.723223  0.039198       3944.0         0.0
4     tech  0.920430  0.039371  0.783232  0.127031       9486.0         0.0
5  OVERALL  0.564522  0.075773  0.439168  0.036997          NaN         NaN

In [16]:
model_mine = exp.model

In [9]:
print(
    "Zeros no exp.model:"
)

total = 0
zeros = 0

for name, param in exp.model.named_parameters():

    if (
        "trainable_nn" in name
        and "linear.weight" in name
    ):

        total += param.numel()
        zeros += (param == 0).sum().item()

print("Total:", total)
print("Zeros:", zeros)
print(
    "Sparsity:",
    100 * zeros / total
)

Zeros no exp.model:
Total: 16777216
Zeros: 15099494
Sparsity: 89.99999761581421

Pruning 90% pytorch link1

In [8]:
import torch.nn.utils.prune as prune

In [9]:
exp = Exp(handler)

exp.prepare_model()

exp.load_model("pretrain_link1")

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 15:53:05.020667: Loaded pretrain_link1

In [10]:
parameters_to_prune = []

for name, module in exp.model.named_modules():

    if isinstance(module, t.nn.Linear):

        if "trainable_nn" in name:

            parameters_to_prune.append(
                (module, "weight")
            )

print(len(parameters_to_prune))

64

In [11]:
total = 0
zeros = 0

for module, name in parameters_to_prune:

    weight = getattr(module, name)

    total += weight.numel()
    zeros += (weight == 0).sum().item()

print("Total:", total)
print("Zeros:", zeros)
print("Sparsity:", 100 * zeros / total)

Total: 16777216
Zeros: 0
Sparsity: 0.0

In [12]:
prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.90
)

In [13]:
total = 0
zeros = 0

for module, name in parameters_to_prune:

    weight = getattr(module, name)

    total += weight.numel()
    zeros += (weight == 0).sum().item()

print("Total:", total)
print("Zeros:", zeros)
print("Sparsity:", 100 * zeros / total)

Total: 16777216
Zeros: 15099494
Sparsity: 89.99999761581421

In [17]:
exp = Exp(handler)

exp.prepare_model()

exp.load_model("pretrain_link1")

parameters_to_prune = []

for name, module in exp.model.named_modules():

    if (
        isinstance(module, t.nn.Linear)
        and "trainable_nn" in name
    ):
        parameters_to_prune.append(
            (module, "weight")
        )

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.90
)

df = exp.evaluate()

print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 16:12:52.179452: Loaded pretrain_link1
2026-08-12 16:13:17.008332: Epoch 100/100, arxiv Test: Acc_mean = 0.5393, Acc_std = 0.1043, F1_mean = 0.3987, F1_std = 0.0456, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 16:13:19.755198: Epoch 100/100, cora Test: Acc_mean = 0.5716, Acc_std = 0.0312, F1_mean = 0.5128, F1_std = 0.0266, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 16:13:21.540791: Epoch 100/100, home Test: Acc_mean = 0.6178, Acc_std = 0.0504, F1_mean = 0.4088, F1_std = 0.0896, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 16:13:23.873471: Epoch 100/100, pubmed Test: Acc_mean = 0.7756, Acc_std = 0.0177, F1_mean = 0.7573, F1_std = 0.0211, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 16:16:14.815788: Epoch 100/100, tech Test: Acc_mean = 0.8879, Acc_std = 0.1069, F1_mean = 0.7946, F1_std = 0.1702, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 16:16:14.816809: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6061, Acc_std = 0.0893, F1_mean = 0.4814, F1_std = 0.0569
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.539321  0.104264  0.398666  0.045630      48603.0         0.0
1     cora  0.571588  0.031178  0.512767  0.026631       3414.0         0.0
2     home  0.617773  0.050440  0.408812  0.089579       1958.0         0.0
3   pubmed  0.775609  0.017741  0.757343  0.021141       3944.0         0.0
4     tech  0.887856  0.106941  0.794576  0.170219       9486.0         0.0
5  OVERALL  0.606109  0.089277  0.481444  0.056940          NaN         NaN

In [18]:
model_torch = exp.model

Teste das mascaras

In [24]:
def compare_masks(model_mine, model_torch):

    results = []

    modules_torch = dict(model_torch.named_modules())

    for name, param in model_mine.named_parameters():

        if "trainable_nn" not in name or "linear.weight" not in name:
            continue

        module_name = name.replace(".weight", "")

        mask_mine = param.detach() != 0

        mask_torch = modules_torch[
            module_name
        ].weight_mask.detach().bool()

        different = (
            mask_mine.cpu() != mask_torch.cpu()
        ).sum().item()

        total = mask_mine.numel()

        results.append({
            "Layer": name,
            "Different": different,
            "Different (%)": 100 * different / total,
            "Same": different == 0
        })

    return pd.DataFrame(results)

In [25]:
df_masks = compare_masks(
    pruner_mine.model,
    model_torch
)

df_masks

,Layer,Different,Different (%),Same
0,experts.0.trainable_nn.dense_layers.0.linear.w...,0,0.0,True
1,experts.0.trainable_nn.dense_layers.1.linear.w...,0,0.0,True
2,experts.0.trainable_nn.dense_layers.2.linear.w...,0,0.0,True
3,experts.0.trainable_nn.dense_layers.3.linear.w...,0,0.0,True
4,experts.0.trainable_nn.dense_layers.4.linear.w...,0,0.0,True
...,...,...,...,...
59,experts.7.trainable_nn.dense_layers.3.linear.w...,0,0.0,True
60,experts.7.trainable_nn.dense_layers.4.linear.w...,0,0.0,True
61,experts.7.trainable_nn.dense_layers.5.linear.w...,0,0.0,True
62,experts.7.trainable_nn.dense_layers.6.linear.w...,0,0.0,True
63,experts.7.trainable_nn.dense_layers.7.linear.w...,0,0.0,True

In [26]:
print(
    "Camadas idênticas:",
    df_masks["Same"].sum(),
    "/",
    len(df_masks)
)

print(
    "Diferença média:",
    df_masks["Different (%)"].mean()
)

print(
    "Diferença máxima:",
    df_masks["Different (%)"].max()
)

Camadas idênticas: 64 / 64
Diferença média: 0.0
Diferença máxima: 0.0

In [27]:
mask_mine = []
mask_torch = []

for name, param in pruner_mine.model.named_parameters():

    if "trainable_nn" not in name or "linear.weight" not in name:
        continue

    module_name = name.replace(".weight", "")

    mask_mine.append(
        (param.detach() != 0).flatten().cpu()
    )

    mask_torch.append(
        dict(model_torch.named_modules())[
            module_name
        ].weight_mask.detach().bool().flatten().cpu()
    )

mask_mine = t.cat(mask_mine)
mask_torch = t.cat(mask_torch)

print("Nossa sparsidade:",
      100 * (~mask_mine).float().mean().item())

print("PyTorch sparsidade:",
      100 * (~mask_torch).float().mean().item())

print("Máscaras exatamente iguais:",
      t.equal(mask_mine, mask_torch))

Nossa sparsidade: 89.99999761581421
PyTorch sparsidade: 89.99999761581421
Máscaras exatamente iguais: True

In [28]:
def compare_weights(model_mine, model_torch):

    results = []

    modules_torch = dict(model_torch.named_modules())

    for name, param in model_mine.named_parameters():

        if "trainable_nn" not in name or "linear.weight" not in name:
            continue

        module_name = name.replace(".weight", "")

        weight_mine = param.detach().cpu()

        weight_torch = modules_torch[
            module_name
        ].weight.detach().cpu()

        diff = (weight_mine - weight_torch).abs()

        results.append({
            "Layer": name,
            "Max Difference": diff.max().item(),
            "Mean Difference": diff.mean().item(),
            "Different Values": (diff > 0).sum().item()
        })

    return pd.DataFrame(results)

In [29]:
df_weights = compare_weights(
    pruner_mine.model,
    model_torch
)

df_weights

,Layer,Max Difference,Mean Difference,Different Values
0,experts.0.trainable_nn.dense_layers.0.linear.w...,0.0,0.0,0
1,experts.0.trainable_nn.dense_layers.1.linear.w...,0.0,0.0,0
2,experts.0.trainable_nn.dense_layers.2.linear.w...,0.0,0.0,0
3,experts.0.trainable_nn.dense_layers.3.linear.w...,0.0,0.0,0
4,experts.0.trainable_nn.dense_layers.4.linear.w...,0.0,0.0,0
...,...,...,...,...
59,experts.7.trainable_nn.dense_layers.3.linear.w...,0.0,0.0,0
60,experts.7.trainable_nn.dense_layers.4.linear.w...,0.0,0.0,0
61,experts.7.trainable_nn.dense_layers.5.linear.w...,0.0,0.0,0
62,experts.7.trainable_nn.dense_layers.6.linear.w...,0.0,0.0,0
63,experts.7.trainable_nn.dense_layers.7.linear.w...,0.0,0.0,0

In [30]:
print(
    "Maior diferença:",
    df_weights["Max Difference"].max()
)

print(
    "Diferença média:",
    df_weights["Mean Difference"].mean()
)

print(
    "Valores diferentes:",
    df_weights["Different Values"].sum()
)

Maior diferença: 0.0
Diferença média: 0.0
Valores diferentes: 0

Teste de aleatoriedade

In [31]:
exp = Exp(handler)
exp.prepare_model()
exp.load_model("pretrain_link1")

pruner = GlobalMagnitudePruner(exp.model)

exp.model = pruner.prune(0.90)

df1 = exp.evaluate()
df2 = exp.evaluate()

print("Primeira:")
print(df1)

print("\nSegunda:")
print(df2)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 16:31:53.766391: Loaded pretrain_link1
Global Pruning: 90.0%
Threshold: 0.04173007
2026-08-12 16:32:39.977867: Epoch 100/100, arxiv Test: Acc_mean = 0.5504, Acc_std = 0.0432, F1_mean = 0.3621, F1_std = 0.0608, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 16:32:45.657849: Epoch 100/100, cora Test: Acc_mean = 0.5660, Acc_std = 0.0065, F1_mean = 0.5112, F1_std = 0.0130, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 16:32:51.723546: Epoch 100/100, home Test: Acc_mean = 0.5948, Acc_std = 0.0655, F1_mean = 0.3685, F1_std = 0.0522, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 16:32:54.179099: Epoch 100/100, pubmed Test: Acc_mean = 0.7647, Acc_std = 0.0187, F1_mean = 0.7480, F1_std = 0.0200, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 16:36:35.152743: Epoch 100/100, tech Test: Acc_mean = 0.9355, Acc_std = 0.0263, F1_mean = 0.8568, F1_std = 0.0698, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 16:36:35.154880: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6192, Acc_std = 0.0345, F1_mean = 0.4621, F1_std = 0.0537
2026-08-12 16:37:43.678364: Epoch 100/100, arxiv Test: Acc_mean = 0.5333, Acc_std = 0.0976, F1_mean = 0.3718, F1_std = 0.0554, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 16:37:46.323887: Epoch 100/100, cora Test: Acc_mean = 0.5695, Acc_std = 0.0142, F1_mean = 0.5166, F1_std = 0.0173, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 16:37:47.839472: Epoch 100/100, home Test: Acc_mean = 0.6370, Acc_std = 0.0333, F1_mean = 0.4326, F1_std = 0.0816, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 16:37:49.927809: Epoch 100/100, pubmed Test: Acc_mean = 0.7716, Acc_std = 0.0071, F1_mean = 0.7567, F1_std = 0.0152, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 16:40:35.277565: Epoch 100/100, tech Test: Acc_mean = 0.9019, Acc_std = 0.0597, F1_mean = 0.8097, F1_std = 0.0979, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 16:40:35.279568: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6040, Acc_std = 0.0643, F1_mean = 0.4650, F1_std = 0.0270
Primeira:
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.550365  0.043248  0.362138  0.060762      48603.0         0.0
1     cora  0.566022  0.006472  0.511198  0.012979       3414.0         0.0
2     home  0.594791  0.065467  0.368535  0.052177       1958.0         0.0
3   pubmed  0.764655  0.018681  0.748050  0.019959       3944.0         0.0
4     tech  0.935547  0.026265  0.856809  0.069756       9486.0         0.0
5  OVERALL  0.619194  0.034547  0.462069  0.053677          NaN         NaN

Segunda:
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.533292  0.097553  0.371773  0.055371      48603.0         0.0
1     cora  0.569479  0.014181  0.516637  0.017259       3414.0         0.0
2     home  0.636977  0.033322  0.432620  0.081551       1958.0         0.0
3   pubmed  0.771602  0.007093  0.756701  0.015171       3944.0         0.0
4     tech  0.901919  0.059703  0.809681  0.097907       9486.0         0.0
5  OVERALL  0.603958  0.064340  0.465028  0.026954          NaN         NaN

Teste de desempenho do pruning para diferentes espacidades

In [ ]:
import pandas as pd
import torch as t

pruning_levels = [
    0.0, 0.1, 0.2, 0.3, 0.4,
    0.5, 0.6, 0.7, 0.8, 0.9
]

n_repeats = 10
checkpoint = "pretrain_link1"

all_results = []

for sparsity in pruning_levels:

    print("\n" + "=" * 60)
    print(f"Sparsity: {sparsity * 100:.0f}%")
    print("=" * 60)

    for repeat in range(n_repeats):

        print(f"\nRepetição {repeat + 1}/{n_repeats}")

        exp = Exp(handler)

        exp.prepare_model()
        exp.load_model(checkpoint)

        # -----------------------------
        # Pruning
        # -----------------------------

        if sparsity > 0:

            pruner = GlobalMagnitudePruner(exp.model)

            exp.model = pruner.prune(sparsity)

        # -----------------------------
        # Avaliação
        # -----------------------------

        df = exp.evaluate(
            repeat_times=1
        ).copy()

        df["Checkpoint"] = checkpoint
        df["Sparsity"] = sparsity * 100
        df["Repeat"] = repeat + 1

        all_results.append(df)

        del exp

        if sparsity > 0:
            del pruner

        t.cuda.empty_cache()


df_all1 = pd.concat(
    all_results,
    ignore_index=True
)

df_all1

============================================================
Sparsity: 0%
============================================================

Repetição 1/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:47:17.797401: Loaded pretrain_link1
2026-08-12 21:47:22.079028: Epoch 100/100, arxiv Test: Acc_mean = 0.4677, Acc_std = 0.0000, F1_mean = 0.2925, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:47:22.648702: Epoch 100/100, cora Test: Acc_mean = 0.6186, Acc_std = 0.0000, F1_mean = 0.5663, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:47:22.955922: Epoch 100/100, home Test: Acc_mean = 0.6578, Acc_std = 0.0000, F1_mean = 0.3977, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:47:23.377076: Epoch 100/100, pubmed Test: Acc_mean = 0.7561, Acc_std = 0.0000, F1_mean = 0.7313, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:48:09.571580: Epoch 100/100, tech Test: Acc_mean = 0.9284, Acc_std = 0.0000, F1_mean = 0.8930, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:48:09.571580: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5626, Acc_std = 0.0000, F1_mean = 0.4196, F1_std = 0.0000

Repetição 2/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:48:35.290281: Loaded pretrain_link1
2026-08-12 21:48:39.510892: Epoch 100/100, arxiv Test: Acc_mean = 0.5165, Acc_std = 0.0000, F1_mean = 0.3056, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:48:40.066624: Epoch 100/100, cora Test: Acc_mean = 0.6201, Acc_std = 0.0000, F1_mean = 0.5621, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:48:40.374291: Epoch 100/100, home Test: Acc_mean = 0.6313, Acc_std = 0.0000, F1_mean = 0.4764, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:48:40.792931: Epoch 100/100, pubmed Test: Acc_mean = 0.7677, Acc_std = 0.0000, F1_mean = 0.7548, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:49:10.820880: Epoch 100/100, tech Test: Acc_mean = 0.9192, Acc_std = 0.0000, F1_mean = 0.8327, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:49:10.820880: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5965, Acc_std = 0.0000, F1_mean = 0.4240, F1_std = 0.0000

Repetição 3/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:49:34.712427: Loaded pretrain_link1
2026-08-12 21:49:38.864809: Epoch 100/100, arxiv Test: Acc_mean = 0.5324, Acc_std = 0.0000, F1_mean = 0.3091, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:49:39.437960: Epoch 100/100, cora Test: Acc_mean = 0.6057, Acc_std = 0.0000, F1_mean = 0.5571, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:49:39.739274: Epoch 100/100, home Test: Acc_mean = 0.6522, Acc_std = 0.0000, F1_mean = 0.5015, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:49:40.159340: Epoch 100/100, pubmed Test: Acc_mean = 0.6034, Acc_std = 0.0000, F1_mean = 0.5873, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:50:09.842275: Epoch 100/100, tech Test: Acc_mean = 0.9547, Acc_std = 0.0000, F1_mean = 0.8654, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:50:09.842275: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6032, Acc_std = 0.0000, F1_mean = 0.4218, F1_std = 0.0000

Repetição 4/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:50:33.520340: Loaded pretrain_link1
2026-08-12 21:50:37.726666: Epoch 100/100, arxiv Test: Acc_mean = 0.4775, Acc_std = 0.0000, F1_mean = 0.2956, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:50:38.273688: Epoch 100/100, cora Test: Acc_mean = 0.6242, Acc_std = 0.0000, F1_mean = 0.5577, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:50:38.578578: Epoch 100/100, home Test: Acc_mean = 0.6547, Acc_std = 0.0000, F1_mean = 0.4308, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:50:38.994855: Epoch 100/100, pubmed Test: Acc_mean = 0.7642, Acc_std = 0.0000, F1_mean = 0.7557, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:51:08.975176: Epoch 100/100, tech Test: Acc_mean = 0.9549, Acc_std = 0.0000, F1_mean = 0.8888, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:51:08.975176: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5741, Acc_std = 0.0000, F1_mean = 0.4232, F1_std = 0.0000

Repetição 5/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:51:33.425633: Loaded pretrain_link1
2026-08-12 21:51:37.578326: Epoch 100/100, arxiv Test: Acc_mean = 0.5287, Acc_std = 0.0000, F1_mean = 0.2881, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:51:38.153640: Epoch 100/100, cora Test: Acc_mean = 0.6008, Acc_std = 0.0000, F1_mean = 0.5510, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:51:38.458235: Epoch 100/100, home Test: Acc_mean = 0.5766, Acc_std = 0.0000, F1_mean = 0.4356, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:51:38.877807: Epoch 100/100, pubmed Test: Acc_mean = 0.7454, Acc_std = 0.0000, F1_mean = 0.7033, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:52:08.937190: Epoch 100/100, tech Test: Acc_mean = 0.9576, Acc_std = 0.0000, F1_mean = 0.9117, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:52:08.937190: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6068, Acc_std = 0.0000, F1_mean = 0.4178, F1_std = 0.0000

Repetição 6/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:52:32.494651: Loaded pretrain_link1
2026-08-12 21:52:36.684675: Epoch 100/100, arxiv Test: Acc_mean = 0.5221, Acc_std = 0.0000, F1_mean = 0.2973, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:52:37.245079: Epoch 100/100, cora Test: Acc_mean = 0.6227, Acc_std = 0.0000, F1_mean = 0.5640, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:52:37.550882: Epoch 100/100, home Test: Acc_mean = 0.5301, Acc_std = 0.0000, F1_mean = 0.3482, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:52:37.971131: Epoch 100/100, pubmed Test: Acc_mean = 0.7647, Acc_std = 0.0000, F1_mean = 0.7564, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:53:07.978230: Epoch 100/100, tech Test: Acc_mean = 0.9511, Acc_std = 0.0000, F1_mean = 0.8994, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:53:07.978230: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6020, Acc_std = 0.0000, F1_mean = 0.4239, F1_std = 0.0000

Repetição 7/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:53:31.524025: Loaded pretrain_link1
2026-08-12 21:53:35.656557: Epoch 100/100, arxiv Test: Acc_mean = 0.4889, Acc_std = 0.0000, F1_mean = 0.3071, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:53:36.239919: Epoch 100/100, cora Test: Acc_mean = 0.5659, Acc_std = 0.0000, F1_mean = 0.5186, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:53:36.550229: Epoch 100/100, home Test: Acc_mean = 0.6798, Acc_std = 0.0000, F1_mean = 0.5760, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:53:36.973313: Epoch 100/100, pubmed Test: Acc_mean = 0.7259, Acc_std = 0.0000, F1_mean = 0.6973, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:54:12.713805: Epoch 100/100, tech Test: Acc_mean = 0.9505, Acc_std = 0.0000, F1_mean = 0.9021, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:54:12.713805: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5772, Acc_std = 0.0000, F1_mean = 0.4322, F1_std = 0.0000

Repetição 8/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:54:36.459222: Loaded pretrain_link1
2026-08-12 21:54:40.663289: Epoch 100/100, arxiv Test: Acc_mean = 0.5185, Acc_std = 0.0000, F1_mean = 0.3153, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:54:41.206794: Epoch 100/100, cora Test: Acc_mean = 0.6192, Acc_std = 0.0000, F1_mean = 0.5618, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:54:41.518175: Epoch 100/100, home Test: Acc_mean = 0.6016, Acc_std = 0.0000, F1_mean = 0.4045, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:54:41.936007: Epoch 100/100, pubmed Test: Acc_mean = 0.5535, Acc_std = 0.0000, F1_mean = 0.4934, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:55:12.152492: Epoch 100/100, tech Test: Acc_mean = 0.9220, Acc_std = 0.0000, F1_mean = 0.8753, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:55:12.152492: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5849, Acc_std = 0.0000, F1_mean = 0.4196, F1_std = 0.0000

Repetição 9/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:55:35.865099: Loaded pretrain_link1
2026-08-12 21:55:39.997483: Epoch 100/100, arxiv Test: Acc_mean = 0.4970, Acc_std = 0.0000, F1_mean = 0.3130, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:55:40.569857: Epoch 100/100, cora Test: Acc_mean = 0.6160, Acc_std = 0.0000, F1_mean = 0.5612, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:55:40.875829: Epoch 100/100, home Test: Acc_mean = 0.5991, Acc_std = 0.0000, F1_mean = 0.3900, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:55:41.292302: Epoch 100/100, pubmed Test: Acc_mean = 0.7401, Acc_std = 0.0000, F1_mean = 0.7336, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:56:11.299341: Epoch 100/100, tech Test: Acc_mean = 0.8098, Acc_std = 0.0000, F1_mean = 0.7583, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:56:11.299341: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5643, Acc_std = 0.0000, F1_mean = 0.4151, F1_std = 0.0000

Repetição 10/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:56:35.119220: Loaded pretrain_link1
2026-08-12 21:56:39.317974: Epoch 100/100, arxiv Test: Acc_mean = 0.4951, Acc_std = 0.0000, F1_mean = 0.3107, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:56:39.866467: Epoch 100/100, cora Test: Acc_mean = 0.6183, Acc_std = 0.0000, F1_mean = 0.5613, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:56:40.168972: Epoch 100/100, home Test: Acc_mean = 0.6685, Acc_std = 0.0000, F1_mean = 0.4212, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:56:40.584867: Epoch 100/100, pubmed Test: Acc_mean = 0.5900, Acc_std = 0.0000, F1_mean = 0.5250, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:57:15.734771: Epoch 100/100, tech Test: Acc_mean = 0.9312, Acc_std = 0.0000, F1_mean = 0.8956, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:57:15.734771: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5733, Acc_std = 0.0000, F1_mean = 0.4214, F1_std = 0.0000

============================================================
Sparsity: 10%
============================================================

Repetição 1/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:57:40.146892: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 21:57:45.432823: Epoch 100/100, arxiv Test: Acc_mean = 0.5045, Acc_std = 0.0000, F1_mean = 0.3157, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:57:46.005129: Epoch 100/100, cora Test: Acc_mean = 0.6125, Acc_std = 0.0000, F1_mean = 0.5603, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:57:46.307253: Epoch 100/100, home Test: Acc_mean = 0.6221, Acc_std = 0.0000, F1_mean = 0.4852, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:57:46.725181: Epoch 100/100, pubmed Test: Acc_mean = 0.7497, Acc_std = 0.0000, F1_mean = 0.7341, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:58:17.107292: Epoch 100/100, tech Test: Acc_mean = 0.9406, Acc_std = 0.0000, F1_mean = 0.8493, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:58:17.107292: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5891, Acc_std = 0.0000, F1_mean = 0.4326, F1_std = 0.0000

Repetição 2/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:58:41.129569: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 21:58:45.334501: Epoch 100/100, arxiv Test: Acc_mean = 0.4906, Acc_std = 0.0000, F1_mean = 0.3000, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:58:45.877523: Epoch 100/100, cora Test: Acc_mean = 0.6245, Acc_std = 0.0000, F1_mean = 0.5646, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:58:46.179583: Epoch 100/100, home Test: Acc_mean = 0.6149, Acc_std = 0.0000, F1_mean = 0.3827, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:58:46.597124: Epoch 100/100, pubmed Test: Acc_mean = 0.6217, Acc_std = 0.0000, F1_mean = 0.6033, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 21:59:16.335089: Epoch 100/100, tech Test: Acc_mean = 0.9694, Acc_std = 0.0000, F1_mean = 0.9170, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 21:59:16.335089: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5760, Acc_std = 0.0000, F1_mean = 0.4204, F1_std = 0.0000

Repetição 3/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 21:59:41.043329: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 21:59:45.221808: Epoch 100/100, arxiv Test: Acc_mean = 0.4666, Acc_std = 0.0000, F1_mean = 0.2945, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 21:59:45.808535: Epoch 100/100, cora Test: Acc_mean = 0.5495, Acc_std = 0.0000, F1_mean = 0.4994, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 21:59:46.109125: Epoch 100/100, home Test: Acc_mean = 0.5868, Acc_std = 0.0000, F1_mean = 0.3932, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 21:59:46.525243: Epoch 100/100, pubmed Test: Acc_mean = 0.6410, Acc_std = 0.0000, F1_mean = 0.6185, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 22:00:22.141172: Epoch 100/100, tech Test: Acc_mean = 0.9239, Acc_std = 0.0000, F1_mean = 0.8846, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 22:00:22.141172: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5489, Acc_std = 0.0000, F1_mean = 0.4097, F1_std = 0.0000

Repetição 4/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 22:00:47.142253: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 22:00:51.394436: Epoch 100/100, arxiv Test: Acc_mean = 0.4718, Acc_std = 0.0000, F1_mean = 0.2971, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 22:00:51.949686: Epoch 100/100, cora Test: Acc_mean = 0.6134, Acc_std = 0.0000, F1_mean = 0.5529, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 22:00:52.253898: Epoch 100/100, home Test: Acc_mean = 0.6195, Acc_std = 0.0000, F1_mean = 0.4184, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 22:00:52.673417: Epoch 100/100, pubmed Test: Acc_mean = 0.5882, Acc_std = 0.0000, F1_mean = 0.5164, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 22:01:22.447984: Epoch 100/100, tech Test: Acc_mean = 0.9486, Acc_std = 0.0000, F1_mean = 0.9050, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 22:01:22.447984: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5572, Acc_std = 0.0000, F1_mean = 0.4119, F1_std = 0.0000

Repetição 5/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 22:01:47.242961: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 22:01:51.477490: Epoch 100/100, arxiv Test: Acc_mean = 0.5094, Acc_std = 0.0000, F1_mean = 0.3006, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 22:01:52.059028: Epoch 100/100, cora Test: Acc_mean = 0.6169, Acc_std = 0.0000, F1_mean = 0.5603, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 22:01:52.362203: Epoch 100/100, home Test: Acc_mean = 0.6338, Acc_std = 0.0000, F1_mean = 0.4952, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 22:01:52.779635: Epoch 100/100, pubmed Test: Acc_mean = 0.7870, Acc_std = 0.0000, F1_mean = 0.7750, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 22:02:22.563212: Epoch 100/100, tech Test: Acc_mean = 0.9702, Acc_std = 0.0000, F1_mean = 0.9255, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 22:02:22.563212: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5995, Acc_std = 0.0000, F1_mean = 0.4351, F1_std = 0.0000

Repetição 6/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 22:02:46.504693: Loaded pretrain_link1
Global Pruning: 10.0%
Threshold: 0.00082016
2026-08-12 22:02:50.774254: Epoch 100/100, arxiv Test: Acc_mean = 0.5294, Acc_std = 0.0000, F1_mean = 0.3176, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 22:02:51.326048: Epoch 100/100, cora Test: Acc_mean = 0.6069, Acc_std = 0.0000, F1_mean = 0.5462, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 22:02:51.627356: Epoch 100/100, home Test: Acc_mean = 0.6471, Acc_std = 0.0000, F1_mean = 0.4481, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000

,Dataset,Acc_mean,Acc_std,F1_mean,F1_std,tstNum_mean,tstNum_std,Checkpoint,Sparsity,Repeat
0,arxiv,0.467687,0.0,0.292497,0.0,48603.0,0.0,pretrain_link1,0.0,1
1,cora,0.618629,0.0,0.566343,0.0,3414.0,0.0,pretrain_link1,0.0,1
2,home,0.657814,0.0,0.397723,0.0,1958.0,0.0,pretrain_link1,0.0,1
3,pubmed,0.756085,0.0,0.731260,0.0,3944.0,0.0,pretrain_link1,0.0,1
4,tech,0.928421,0.0,0.893005,0.0,9486.0,0.0,pretrain_link1,0.0,1
...,...,...,...,...,...,...,...,...,...,...
595,cora,0.561219,0.0,0.501746,0.0,3414.0,0.0,pretrain_link1,90.0,10
596,home,0.548008,0.0,0.427302,0.0,1958.0,0.0,pretrain_link1,90.0,10
597,pubmed,0.682809,0.0,0.675774,0.0,3944.0,0.0,pretrain_link1,90.0,10
598,tech,0.925364,0.0,0.750744,0.0,9486.0,0.0,pretrain_link1,90.0,10
599,OVERALL,0.574542,0.0,0.378650,0.0,NaN,NaN,pretrain_link1,90.0,10

In [ ]:
df_overall1 = df_all1[
    df_all1["Dataset"] == "OVERALL"
].copy()

summary1 = (
    df_overall1
    .groupby(["Checkpoint", "Sparsity"])
    .agg(
        Acc_mean=("Acc_mean", "mean"),
        Acc_std=("Acc_mean", "std"),
        F1_mean=("F1_mean", "mean"),
        F1_std=("F1_mean", "std")
    )
    .reset_index()
)

summary1

In [ ]:
df_all1.to_csv(
    "pruning_raw_pretrain_link2.csv",
    index=False
)

summary1.to_csv(
    "pruning_summary_pretrain_link2.csv",
    index=False
)

In [ ]:
import pandas as pd
import torch as t

pruning_levels = [
    0.0, 0.1, 0.2, 0.3, 0.4,
    0.5, 0.6, 0.7, 0.8, 0.9
]

n_repeats = 10
checkpoint = "pretrain_link2"

all_results = []

for sparsity in pruning_levels:

    print("\n" + "=" * 60)
    print(f"Sparsity: {sparsity * 100:.0f}%")
    print("=" * 60)

    for repeat in range(n_repeats):

        print(f"\nRepetição {repeat + 1}/{n_repeats}")

        exp = Exp(handler)

        exp.prepare_model()
        exp.load_model(checkpoint)

        # -----------------------------
        # Pruning
        # -----------------------------

        if sparsity > 0:

            pruner = GlobalMagnitudePruner(exp.model)

            exp.model = pruner.prune(sparsity)

        # -----------------------------
        # Avaliação
        # -----------------------------

        df = exp.evaluate(
            repeat_times=1
        ).copy()

        df["Checkpoint"] = checkpoint
        df["Sparsity"] = sparsity * 100
        df["Repeat"] = repeat + 1

        all_results.append(df)

        del exp

        if sparsity > 0:
            del pruner

        t.cuda.empty_cache()


df_all2 = pd.concat(
    all_results,
    ignore_index=True
)

df_all2

============================================================
Sparsity: 0%
============================================================

Repetição 1/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:29:14.406598: Loaded pretrain_link2
2026-08-12 23:29:18.574753: Epoch 100/100, arxiv Test: Acc_mean = 0.6407, Acc_std = 0.0000, F1_mean = 0.3997, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:29:19.152071: Epoch 100/100, cora Test: Acc_mean = 0.6248, Acc_std = 0.0000, F1_mean = 0.5646, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:29:19.457066: Epoch 100/100, home Test: Acc_mean = 0.6726, Acc_std = 0.0000, F1_mean = 0.4486, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:29:19.875019: Epoch 100/100, pubmed Test: Acc_mean = 0.5948, Acc_std = 0.0000, F1_mean = 0.5473, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:29:50.799790: Epoch 100/100, tech Test: Acc_mean = 0.6279, Acc_std = 0.0000, F1_mean = 0.3668, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:29:50.799790: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6363, Acc_std = 0.0000, F1_mean = 0.4135, F1_std = 0.0000

Repetição 2/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:29:52.615984: Loaded pretrain_link2
2026-08-12 23:29:56.799096: Epoch 100/100, arxiv Test: Acc_mean = 0.6509, Acc_std = 0.0000, F1_mean = 0.4089, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:29:57.347541: Epoch 100/100, cora Test: Acc_mean = 0.6271, Acc_std = 0.0000, F1_mean = 0.5669, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:29:57.651443: Epoch 100/100, home Test: Acc_mean = 0.7165, Acc_std = 0.0000, F1_mean = 0.5405, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:29:58.066934: Epoch 100/100, pubmed Test: Acc_mean = 0.7173, Acc_std = 0.0000, F1_mean = 0.7096, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:30:26.926119: Epoch 100/100, tech Test: Acc_mean = 0.9229, Acc_std = 0.0000, F1_mean = 0.8877, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:30:26.927120: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6938, Acc_std = 0.0000, F1_mean = 0.5057, F1_std = 0.0000

Repetição 3/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:30:28.594243: Loaded pretrain_link2
2026-08-12 23:30:32.717256: Epoch 100/100, arxiv Test: Acc_mean = 0.6153, Acc_std = 0.0000, F1_mean = 0.3438, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:30:33.303591: Epoch 100/100, cora Test: Acc_mean = 0.6280, Acc_std = 0.0000, F1_mean = 0.5708, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:30:33.608817: Epoch 100/100, home Test: Acc_mean = 0.6236, Acc_std = 0.0000, F1_mean = 0.3078, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:30:34.024747: Epoch 100/100, pubmed Test: Acc_mean = 0.7001, Acc_std = 0.0000, F1_mean = 0.6985, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:31:02.572570: Epoch 100/100, tech Test: Acc_mean = 0.6061, Acc_std = 0.0000, F1_mean = 0.3173, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:31:02.572570: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6198, Acc_std = 0.0000, F1_mean = 0.3712, F1_std = 0.0000

Repetição 4/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:31:04.189029: Loaded pretrain_link2
2026-08-12 23:31:08.390357: Epoch 100/100, arxiv Test: Acc_mean = 0.6297, Acc_std = 0.0000, F1_mean = 0.3692, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:31:08.936182: Epoch 100/100, cora Test: Acc_mean = 0.6257, Acc_std = 0.0000, F1_mean = 0.5606, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:31:09.238354: Epoch 100/100, home Test: Acc_mean = 0.7349, Acc_std = 0.0000, F1_mean = 0.5062, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:31:09.655055: Epoch 100/100, pubmed Test: Acc_mean = 0.6960, Acc_std = 0.0000, F1_mean = 0.6632, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:31:43.978856: Epoch 100/100, tech Test: Acc_mean = 0.5890, Acc_std = 0.0000, F1_mean = 0.3306, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:31:43.978856: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6307, Acc_std = 0.0000, F1_mean = 0.3946, F1_std = 0.0000

Repetição 5/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:31:45.671427: Loaded pretrain_link2
2026-08-12 23:31:49.804441: Epoch 100/100, arxiv Test: Acc_mean = 0.6343, Acc_std = 0.0000, F1_mean = 0.3892, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:31:50.371945: Epoch 100/100, cora Test: Acc_mean = 0.6204, Acc_std = 0.0000, F1_mean = 0.5580, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:31:50.676357: Epoch 100/100, home Test: Acc_mean = 0.6563, Acc_std = 0.0000, F1_mean = 0.3545, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:31:51.095289: Epoch 100/100, pubmed Test: Acc_mean = 0.6790, Acc_std = 0.0000, F1_mean = 0.6610, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:32:19.744397: Epoch 100/100, tech Test: Acc_mean = 0.8471, Acc_std = 0.0000, F1_mean = 0.8091, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:32:19.744397: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6668, Acc_std = 0.0000, F1_mean = 0.4717, F1_std = 0.0000

Repetição 6/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:32:21.542918: Loaded pretrain_link2
2026-08-12 23:32:25.712059: Epoch 100/100, arxiv Test: Acc_mean = 0.6290, Acc_std = 0.0000, F1_mean = 0.3704, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:32:26.266532: Epoch 100/100, cora Test: Acc_mean = 0.6216, Acc_std = 0.0000, F1_mean = 0.5594, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:32:26.569319: Epoch 100/100, home Test: Acc_mean = 0.6512, Acc_std = 0.0000, F1_mean = 0.3549, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:32:26.992066: Epoch 100/100, pubmed Test: Acc_mean = 0.7622, Acc_std = 0.0000, F1_mean = 0.7493, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:32:55.431261: Epoch 100/100, tech Test: Acc_mean = 0.6745, Acc_std = 0.0000, F1_mean = 0.4266, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:32:55.431261: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6435, Acc_std = 0.0000, F1_mean = 0.4096, F1_std = 0.0000

Repetição 7/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:32:57.065205: Loaded pretrain_link2
2026-08-12 23:33:01.180233: Epoch 100/100, arxiv Test: Acc_mean = 0.6140, Acc_std = 0.0000, F1_mean = 0.3498, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:33:01.756960: Epoch 100/100, cora Test: Acc_mean = 0.6251, Acc_std = 0.0000, F1_mean = 0.5577, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:33:02.060002: Epoch 100/100, home Test: Acc_mean = 0.6527, Acc_std = 0.0000, F1_mean = 0.3843, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:33:02.476579: Epoch 100/100, pubmed Test: Acc_mean = 0.6590, Acc_std = 0.0000, F1_mean = 0.6437, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:33:30.657486: Epoch 100/100, tech Test: Acc_mean = 0.8260, Acc_std = 0.0000, F1_mean = 0.7668, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:33:30.657486: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6482, Acc_std = 0.0000, F1_mean = 0.4372, F1_std = 0.0000

Repetição 8/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:33:32.346302: Loaded pretrain_link2
2026-08-12 23:33:36.507641: Epoch 100/100, arxiv Test: Acc_mean = 0.6353, Acc_std = 0.0000, F1_mean = 0.3811, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:33:37.052437: Epoch 100/100, cora Test: Acc_mean = 0.6312, Acc_std = 0.0000, F1_mean = 0.5634, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:33:37.354262: Epoch 100/100, home Test: Acc_mean = 0.6491, Acc_std = 0.0000, F1_mean = 0.3939, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:33:37.767799: Epoch 100/100, pubmed Test: Acc_mean = 0.7079, Acc_std = 0.0000, F1_mean = 0.6845, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:34:09.260113: Epoch 100/100, tech Test: Acc_mean = 0.5887, Acc_std = 0.0000, F1_mean = 0.2848, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:34:09.261162: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6332, Acc_std = 0.0000, F1_mean = 0.3949, F1_std = 0.0000

Repetição 9/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:34:11.002661: Loaded pretrain_link2
2026-08-12 23:34:15.155795: Epoch 100/100, arxiv Test: Acc_mean = 0.6335, Acc_std = 0.0000, F1_mean = 0.3741, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:34:15.734179: Epoch 100/100, cora Test: Acc_mean = 0.6262, Acc_std = 0.0000, F1_mean = 0.5673, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:34:16.037668: Epoch 100/100, home Test: Acc_mean = 0.6496, Acc_std = 0.0000, F1_mean = 0.4065, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:34:16.454171: Epoch 100/100, pubmed Test: Acc_mean = 0.6833, Acc_std = 0.0000, F1_mean = 0.6619, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:34:44.520494: Epoch 100/100, tech Test: Acc_mean = 0.8440, Acc_std = 0.0000, F1_mean = 0.8038, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:34:44.520494: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6662, Acc_std = 0.0000, F1_mean = 0.4622, F1_std = 0.0000

Repetição 10/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:34:46.181714: Loaded pretrain_link2
2026-08-12 23:34:50.358507: Epoch 100/100, arxiv Test: Acc_mean = 0.6319, Acc_std = 0.0000, F1_mean = 0.3735, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:34:50.905619: Epoch 100/100, cora Test: Acc_mean = 0.6248, Acc_std = 0.0000, F1_mean = 0.5627, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:34:51.208947: Epoch 100/100, home Test: Acc_mean = 0.6639, Acc_std = 0.0000, F1_mean = 0.4260, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:34:51.624337: Epoch 100/100, pubmed Test: Acc_mean = 0.7003, Acc_std = 0.0000, F1_mean = 0.6914, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:35:19.741707: Epoch 100/100, tech Test: Acc_mean = 0.7367, Acc_std = 0.0000, F1_mean = 0.5819, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:35:19.741707: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6512, Acc_std = 0.0000, F1_mean = 0.4326, F1_std = 0.0000

============================================================
Sparsity: 10%
============================================================

Repetição 1/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:35:21.396416: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:35:25.559356: Epoch 100/100, arxiv Test: Acc_mean = 0.6114, Acc_std = 0.0000, F1_mean = 0.3627, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:35:26.143037: Epoch 100/100, cora Test: Acc_mean = 0.6224, Acc_std = 0.0000, F1_mean = 0.5581, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:35:26.442976: Epoch 100/100, home Test: Acc_mean = 0.6660, Acc_std = 0.0000, F1_mean = 0.4234, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:35:26.863389: Epoch 100/100, pubmed Test: Acc_mean = 0.7092, Acc_std = 0.0000, F1_mean = 0.6965, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:35:54.901672: Epoch 100/100, tech Test: Acc_mean = 0.7059, Acc_std = 0.0000, F1_mean = 0.5076, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:35:54.901672: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6326, Acc_std = 0.0000, F1_mean = 0.4143, F1_std = 0.0000

Repetição 2/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:35:56.574810: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:36:00.779141: Epoch 100/100, arxiv Test: Acc_mean = 0.6215, Acc_std = 0.0000, F1_mean = 0.3742, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:36:01.321659: Epoch 100/100, cora Test: Acc_mean = 0.6280, Acc_std = 0.0000, F1_mean = 0.5628, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:36:01.621696: Epoch 100/100, home Test: Acc_mean = 0.6517, Acc_std = 0.0000, F1_mean = 0.4325, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:36:02.038108: Epoch 100/100, pubmed Test: Acc_mean = 0.7110, Acc_std = 0.0000, F1_mean = 0.7112, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:36:29.971814: Epoch 100/100, tech Test: Acc_mean = 0.6910, Acc_std = 0.0000, F1_mean = 0.5352, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:36:29.971814: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6377, Acc_std = 0.0000, F1_mean = 0.4278, F1_std = 0.0000

Repetição 3/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:36:31.637639: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:36:35.769908: Epoch 100/100, arxiv Test: Acc_mean = 0.6423, Acc_std = 0.0000, F1_mean = 0.3940, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:36:36.346327: Epoch 100/100, cora Test: Acc_mean = 0.6271, Acc_std = 0.0000, F1_mean = 0.5641, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:36:36.646175: Epoch 100/100, home Test: Acc_mean = 0.6670, Acc_std = 0.0000, F1_mean = 0.3670, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:36:37.061282: Epoch 100/100, pubmed Test: Acc_mean = 0.7647, Acc_std = 0.0000, F1_mean = 0.7428, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:37:18.094231: Epoch 100/100, tech Test: Acc_mean = 0.8504, Acc_std = 0.0000, F1_mean = 0.7974, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:37:18.094231: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6787, Acc_std = 0.0000, F1_mean = 0.4790, F1_std = 0.0000

Repetição 4/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:37:19.838895: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:37:24.053573: Epoch 100/100, arxiv Test: Acc_mean = 0.6154, Acc_std = 0.0000, F1_mean = 0.3657, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:37:24.592508: Epoch 100/100, cora Test: Acc_mean = 0.6227, Acc_std = 0.0000, F1_mean = 0.5647, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:37:24.893961: Epoch 100/100, home Test: Acc_mean = 0.6706, Acc_std = 0.0000, F1_mean = 0.4471, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:37:25.311210: Epoch 100/100, pubmed Test: Acc_mean = 0.7150, Acc_std = 0.0000, F1_mean = 0.7131, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:37:59.114250: Epoch 100/100, tech Test: Acc_mean = 0.8432, Acc_std = 0.0000, F1_mean = 0.7922, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:37:59.114250: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6553, Acc_std = 0.0000, F1_mean = 0.4585, F1_std = 0.0000

Repetição 5/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:38:00.927207: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:38:05.092331: Epoch 100/100, arxiv Test: Acc_mean = 0.6421, Acc_std = 0.0000, F1_mean = 0.3919, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:38:05.669770: Epoch 100/100, cora Test: Acc_mean = 0.6087, Acc_std = 0.0000, F1_mean = 0.5484, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:38:05.971917: Epoch 100/100, home Test: Acc_mean = 0.6685, Acc_std = 0.0000, F1_mean = 0.4178, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-12 23:38:06.392199: Epoch 100/100, pubmed Test: Acc_mean = 0.6935, Acc_std = 0.0000, F1_mean = 0.6895, F1_std = 0.0000, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-12 23:38:34.332781: Epoch 100/100, tech Test: Acc_mean = 0.8404, Acc_std = 0.0000, F1_mean = 0.7996, F1_std = 0.0000, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-12 23:38:34.332781: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6721, Acc_std = 0.0000, F1_mean = 0.4754, F1_std = 0.0000

Repetição 6/10
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-12 23:38:35.959381: Loaded pretrain_link2
Global Pruning: 10.0%
Threshold: 0.00000000
2026-08-12 23:38:40.164771: Epoch 100/100, arxiv Test: Acc_mean = 0.6420, Acc_std = 0.0000, F1_mean = 0.3885, F1_std = 0.0000, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-12 23:38:40.706169: Epoch 100/100, cora Test: Acc_mean = 0.6183, Acc_std = 0.0000, F1_mean = 0.5510, F1_std = 0.0000, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-12 23:38:41.008734: Epoch 100/100, home Test: Acc_mean = 0.6767, Acc_std = 0.0000, F1_mean = 0.4476, F1_std = 0.0000, tstNum_mean = 1958.0000, tstNum_std = 0.0000

,Dataset,Acc_mean,Acc_std,F1_mean,F1_std,tstNum_mean,tstNum_std,Checkpoint,Sparsity,Repeat
0,arxiv,0.640681,0.0,0.399745,0.0,48603.0,0.0,pretrain_link2,0.0,1
1,cora,0.624780,0.0,0.564576,0.0,3414.0,0.0,pretrain_link2,0.0,1
2,home,0.672625,0.0,0.448605,0.0,1958.0,0.0,pretrain_link2,0.0,1
3,pubmed,0.594828,0.0,0.547260,0.0,3944.0,0.0,pretrain_link2,0.0,1
4,tech,0.627873,0.0,0.366837,0.0,9486.0,0.0,pretrain_link2,0.0,1
...,...,...,...,...,...,...,...,...,...,...
595,cora,0.617458,0.0,0.556859,0.0,3414.0,0.0,pretrain_link2,90.0,10
596,home,0.734934,0.0,0.514504,0.0,1958.0,0.0,pretrain_link2,90.0,10
597,pubmed,0.649087,0.0,0.591828,0.0,3944.0,0.0,pretrain_link2,90.0,10
598,tech,0.874657,0.0,0.833903,0.0,9486.0,0.0,pretrain_link2,90.0,10
599,OVERALL,0.670292,0.0,0.506470,0.0,NaN,NaN,pretrain_link2,90.0,10

In [11]:
df_overall2 = df_all[
    df_all["Dataset"] == "OVERALL"
].copy()

summary2 = (
    df_overall2
    .groupby(["Checkpoint", "Sparsity"])
    .agg(
        Acc_mean=("Acc_mean", "mean"),
        Acc_std=("Acc_mean", "std"),
        F1_mean=("F1_mean", "mean"),
        F1_std=("F1_mean", "std")
    )
    .reset_index()
)

summary2

       Checkpoint  Sparsity  Acc_mean   Acc_std   F1_mean    F1_std
0  pretrain_link2       0.0  0.648964  0.021732  0.429332  0.041083
1  pretrain_link2      10.0  0.651544  0.017688  0.442988  0.029925
2  pretrain_link2      20.0  0.651173  0.018018  0.437963  0.035522
3  pretrain_link2      30.0  0.656104  0.013865  0.452426  0.025211
4  pretrain_link2      40.0  0.656696  0.015484  0.450927  0.026588
5  pretrain_link2      50.0  0.658742  0.016768  0.464640  0.030472
6  pretrain_link2      60.0  0.649477  0.014740  0.475853  0.021831
7  pretrain_link2      70.0  0.650370  0.015239  0.481704  0.029183
8  pretrain_link2      80.0  0.659570  0.012983  0.495667  0.021567
9  pretrain_link2      90.0  0.663943  0.012252  0.504859  0.013507

In [ ]:
df_all2.to_csv(
    "pruning_raw_pretrain_link2.csv",
    index=False
)

summary2.to_csv(
    "pruning_summary_pretrain_link2.csv",
    index=False
)

Para reorganizar o codigoa baixo

In [13]:
report = pruner.sparsity_report()

report

{'Threshold': 0.005316588096320629,
 'Requested Sparsity (%)': 30.0,
 'Total': 16777216,
 'Zero': 5033166,
 'Remaining': 11744050,
 'Sparsity (%)': 30.000007152557373}

In [11]:
checkpoint="pretrain_link1"

exp = Exp(handler)

exp.prepare_model()

exp.load_model(checkpoint)

pruner = GlobalMagnitudePruner(exp.model)

pruner.prune(0.30)

exp.model = pruner.get_model()

df = exp.evaluate()

print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-10 17:15:21.693231: Loaded pretrain_link1
Global Magnitude Pruning: 30.0%
Threshold = 0.00531659
2026-08-10 17:15:43.967969: Epoch 100/100, arxiv Test: Acc_mean = 0.4937, Acc_std = 0.0226, F1_mean = 0.3091, F1_std = 0.0098, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-10 17:15:46.584746: Epoch 100/100, cora Test: Acc_mean = 0.6113, Acc_std = 0.0193, F1_mean = 0.5522, F1_std = 0.0179, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-10 17:15:48.139989: Epoch 100/100, home Test: Acc_mean = 0.6380, Acc_std = 0.0707, F1_mean = 0.3920, F1_std = 0.0947, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-10 17:15:50.255801: Epoch 100/100, pubmed Test: Acc_mean = 0.7130, Acc_std = 0.0498, F1_mean = 0.6861, F1_std = 0.0522, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-10 17:18:57.936673: Epoch 100/100, tech Test: Acc_mean = 0.9242, Acc_std = 0.0503, F1_mean = 0.8605, F1_std = 0.0746, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-10 17:18:57.936673: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5773, Acc_std = 0.0172, F1_mean = 0.4235, F1_std = 0.0104
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.493718  0.022624  0.309134  0.009753      48603.0         0.0
1     cora  0.611306  0.019299  0.552238  0.017851       3414.0         0.0
2     home  0.637998  0.070724  0.392049  0.094665       1958.0         0.0
3   pubmed  0.713032  0.049765  0.686128  0.052160       3944.0         0.0
4     tech  0.924225  0.050310  0.860475  0.074574       9486.0         0.0
5  OVERALL  0.577284  0.017215  0.423505  0.010370          NaN         NaN

In [12]:
for checkpoint in ["pretrain_link1", "pretrain_link2"]:
    exp = Exp(handler)

    exp.prepare_model()

    exp.load_model(checkpoint)

    df = exp.evaluate()

    print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 17:46:31.639752: Loaded pretrain_link1
2026-08-07 17:46:52.152254: Epoch 100/100, arxiv Test: Acc_mean = 0.5024, Acc_std = 0.0125, F1_mean = 0.3010, F1_std = 0.0157, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 17:46:54.737893: Epoch 100/100, cora Test: Acc_mean = 0.6062, Acc_std = 0.0211, F1_mean = 0.5516, F1_std = 0.0208, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 17:46:56.286861: Epoch 100/100, home Test: Acc_mean = 0.6520, Acc_std = 0.0656, F1_mean = 0.4375, F1_std = 0.1014, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 17:46:58.387732: Epoch 100/100, pubmed Test: Acc_mean = 0.7145, Acc_std = 0.0488, F1_mean = 0.6738, F1_std = 0.0542, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 17:49:33.303974: Epoch 100/100, tech Test: Acc_mean = 0.8644, Acc_std = 0.0584, F1_mean = 0.7791, F1_std = 0.0884, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 17:49:33.303974: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5754, Acc_std = 0.0105, F1_mean = 0.4067, F1_std = 0.0210
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.502426  0.012534  0.300955  0.015668      48603.0         0.0
1    cora  0.606210  0.021119  0.551649  0.020847       3414.0         0.0
2    home  0.651992  0.065644  0.437513  0.101422       1958.0         0.0
3  pubmed  0.714503  0.048829  0.673819  0.054187       3944.0         0.0
4    tech  0.864432  0.058415  0.779108  0.088364       9486.0         0.0
5     NaN  0.575382  0.010477  0.406728  0.020953          NaN         NaN
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 17:49:42.804391: Loaded pretrain_link2
2026-08-07 17:50:03.358737: Epoch 100/100, arxiv Test: Acc_mean = 0.6316, Acc_std = 0.0068, F1_mean = 0.3798, F1_std = 0.0081, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 17:50:05.950510: Epoch 100/100, cora Test: Acc_mean = 0.6240, Acc_std = 0.0049, F1_mean = 0.5603, F1_std = 0.0037, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 17:50:07.480120: Epoch 100/100, home Test: Acc_mean = 0.6313, Acc_std = 0.0264, F1_mean = 0.3800, F1_std = 0.0383, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 17:50:09.601623: Epoch 100/100, pubmed Test: Acc_mean = 0.7044, Acc_std = 0.0202, F1_mean = 0.6851, F1_std = 0.0309, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 17:52:46.300404: Epoch 100/100, tech Test: Acc_mean = 0.7655, Acc_std = 0.0966, F1_mean = 0.6379, F1_std = 0.1998, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 17:52:46.300404: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6543, Acc_std = 0.0151, F1_mean = 0.4432, F1_std = 0.0271
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.631554  0.006832  0.379838  0.008082      48603.0         0.0
1    cora  0.624019  0.004889  0.560272  0.003690       3414.0         0.0
2    home  0.631256  0.026398  0.380023  0.038281       1958.0         0.0
3  pubmed  0.704412  0.020240  0.685071  0.030879       3944.0         0.0
4    tech  0.765549  0.096644  0.637898  0.199807       9486.0         0.0
5     NaN  0.654284  0.015054  0.443159  0.027110          NaN         NaN

In [ ]:
exp = Exp(handler)
    
exp.prepare_model()
    
exp.load_model(checkpoint)

pruner = GlobalMagnitudePruner(exp.model)

pruner.prune(0.10)

df = exp.evaluate()

print(df)

In [18]:
for checkpoint in ["pretrain_link1", "pretrain_link2"]:

    exp = Exp(handler)
    
    exp.prepare_model()
    
    exp.load_model(checkpoint)

    pruner = GlobalMagnitudePruner(exp.model)

    pruner.prune(0.10)

    df = exp.evaluate()

    print(checkpoint)

    print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:02:50.730356: Loaded pretrain_link1
Threshold = 0.000820
2026-08-07 19:03:11.009694: Epoch 100/100, arxiv Test: Acc_mean = 0.5064, Acc_std = 0.0075, F1_mean = 0.3056, F1_std = 0.0087, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:03:13.544945: Epoch 100/100, cora Test: Acc_mean = 0.6040, Acc_std = 0.0213, F1_mean = 0.5477, F1_std = 0.0166, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:03:15.045403: Epoch 100/100, home Test: Acc_mean = 0.6524, Acc_std = 0.0437, F1_mean = 0.4926, F1_std = 0.0739, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:03:17.130510: Epoch 100/100, pubmed Test: Acc_mean = 0.6745, Acc_std = 0.0419, F1_mean = 0.6356, F1_std = 0.0377, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:05:31.113575: Epoch 100/100, tech Test: Acc_mean = 0.9288, Acc_std = 0.0157, F1_mean = 0.8800, F1_std = 0.0181, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:05:31.113575: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5849, Acc_std = 0.0062, F1_mean = 0.4234, F1_std = 0.0053
pretrain_link1
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.506434  0.007541  0.305562  0.008668      48603.0         0.0
1    cora  0.604042  0.021288  0.547725  0.016624       3414.0         0.0
2    home  0.652400  0.043740  0.492579  0.073943       1958.0         0.0
3  pubmed  0.674493  0.041875  0.635597  0.037668       3944.0         0.0
4    tech  0.928758  0.015700  0.880013  0.018095       9486.0         0.0
5     NaN  0.584885  0.006159  0.423414  0.005331          NaN         NaN
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:05:41.632574: Loaded pretrain_link2
Threshold = 0.000000
2026-08-07 19:06:01.928634: Epoch 100/100, arxiv Test: Acc_mean = 0.6225, Acc_std = 0.0107, F1_mean = 0.3771, F1_std = 0.0345, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:06:04.482326: Epoch 100/100, cora Test: Acc_mean = 0.6234, Acc_std = 0.0021, F1_mean = 0.5584, F1_std = 0.0043, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:06:05.987493: Epoch 100/100, home Test: Acc_mean = 0.6541, Acc_std = 0.0170, F1_mean = 0.3918, F1_std = 0.0343, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:06:08.072288: Epoch 100/100, pubmed Test: Acc_mean = 0.6995, Acc_std = 0.0275, F1_mean = 0.6880, F1_std = 0.0293, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:08:20.670482: Epoch 100/100, tech Test: Acc_mean = 0.7751, Acc_std = 0.0850, F1_mean = 0.6794, F1_std = 0.1585, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:08:20.670482: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6495, Acc_std = 0.0038, F1_mean = 0.4475, F1_std = 0.0046
pretrain_link2
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.622513  0.010693  0.377142  0.034467      48603.0         0.0
1    cora  0.623433  0.002051  0.558384  0.004331       3414.0         0.0
2    home  0.654137  0.017002  0.391769  0.034325       1958.0         0.0
3  pubmed  0.699544  0.027461  0.688026  0.029314       3944.0         0.0
4    tech  0.775079  0.085008  0.679422  0.158468       9486.0         0.0
5     NaN  0.649456  0.003797  0.447478  0.004623          NaN         NaN

In [19]:
for checkpoint in ["pretrain_link1", "pretrain_link2"]:

    exp = Exp(handler)
    
    exp.prepare_model()
    
    exp.load_model(checkpoint)

    pruner = GlobalMagnitudePruner(exp.model)

    pruner.prune(0.20)

    df = exp.evaluate()

    print(checkpoint)

    print(df)

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:08:44.650856: Loaded pretrain_link1
Threshold = 0.002704
2026-08-07 19:09:04.846822: Epoch 100/100, arxiv Test: Acc_mean = 0.4982, Acc_std = 0.0090, F1_mean = 0.3053, F1_std = 0.0109, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:09:07.391998: Epoch 100/100, cora Test: Acc_mean = 0.5954, Acc_std = 0.0248, F1_mean = 0.5396, F1_std = 0.0222, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:09:08.895218: Epoch 100/100, home Test: Acc_mean = 0.6284, Acc_std = 0.0714, F1_mean = 0.4160, F1_std = 0.1203, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:09:10.969125: Epoch 100/100, pubmed Test: Acc_mean = 0.7204, Acc_std = 0.0576, F1_mean = 0.6977, F1_std = 0.0553, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:11:22.543953: Epoch 100/100, tech Test: Acc_mean = 0.9468, Acc_std = 0.0141, F1_mean = 0.8934, F1_std = 0.0145, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:11:22.543953: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5831, Acc_std = 0.0068, F1_mean = 0.4261, F1_std = 0.0106
pretrain_link1
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.498237  0.009021  0.305278  0.010903      48603.0         0.0
1    cora  0.595372  0.024844  0.539558  0.022233       3414.0         0.0
2    home  0.628396  0.071352  0.416038  0.120333       1958.0         0.0
3  pubmed  0.720436  0.057554  0.697672  0.055343       3944.0         0.0
4    tech  0.946785  0.014146  0.893400  0.014492       9486.0         0.0
5     NaN  0.583064  0.006817  0.426089  0.010643          NaN         NaN
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:11:31.952502: Loaded pretrain_link2
Threshold = 0.000000
2026-08-07 19:11:52.016607: Epoch 100/100, arxiv Test: Acc_mean = 0.6294, Acc_std = 0.0095, F1_mean = 0.3789, F1_std = 0.0130, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:11:54.559938: Epoch 100/100, cora Test: Acc_mean = 0.6238, Acc_std = 0.0039, F1_mean = 0.5624, F1_std = 0.0036, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:11:56.057185: Epoch 100/100, home Test: Acc_mean = 0.6403, Acc_std = 0.0242, F1_mean = 0.3689, F1_std = 0.0116, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:11:58.137709: Epoch 100/100, pubmed Test: Acc_mean = 0.6652, Acc_std = 0.0153, F1_mean = 0.6397, F1_std = 0.0259, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:14:10.014866: Epoch 100/100, tech Test: Acc_mean = 0.7954, Acc_std = 0.0775, F1_mean = 0.7169, F1_std = 0.1312, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:14:10.014866: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.6549, Acc_std = 0.0143, F1_mean = 0.4507, F1_std = 0.0236
pretrain_link2
  Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0   arxiv  0.629447  0.009463  0.378889  0.012999      48603.0         0.0
1    cora  0.623843  0.003866  0.562385  0.003638       3414.0         0.0
2    home  0.640347  0.024235  0.368925  0.011636       1958.0         0.0
3  pubmed  0.665162  0.015296  0.639723  0.025874       3944.0         0.0
4    tech  0.795425  0.077472  0.716867  0.131186       9486.0         0.0
5     NaN  0.654928  0.014295  0.450719  0.023559          NaN         NaN

In [8]:
for checkpoint in ["pretrain_link1", "pretrain_link2"]:

    exp = Exp(handler)

    exp.prepare_model()

    exp.load_model("pretrain_link1")

    pruner = GlobalMagnitudePruner(exp.model)

    pruner.prune(0.30)

    exp.model = pruner.get_model()

    df = exp.evaluate()

    print(df)
    print(30*"==")

['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:39:58.539014: Loaded pretrain_link1
Global Magnitude Pruning: 30.0%
Threshold = 0.00531659
2026-08-07 19:40:19.090462: Epoch 100/100, arxiv Test: Acc_mean = 0.4950, Acc_std = 0.0123, F1_mean = 0.2956, F1_std = 0.0073, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:40:21.764268: Epoch 100/100, cora Test: Acc_mean = 0.6067, Acc_std = 0.0166, F1_mean = 0.5517, F1_std = 0.0179, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:40:23.256014: Epoch 100/100, home Test: Acc_mean = 0.6795, Acc_std = 0.0419, F1_mean = 0.4548, F1_std = 0.0647, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:40:25.351067: Epoch 100/100, pubmed Test: Acc_mean = 0.6591, Acc_std = 0.0507, F1_mean = 0.6186, F1_std = 0.0671, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:42:47.324788: Epoch 100/100, tech Test: Acc_mean = 0.9066, Acc_std = 0.0279, F1_mean = 0.8384, F1_std = 0.0354, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:42:47.324788: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5736, Acc_std = 0.0141, F1_mean = 0.4085, F1_std = 0.0101
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.495031  0.012321  0.295639  0.007324      48603.0         0.0
1     cora  0.606678  0.016610  0.551716  0.017915       3414.0         0.0
2     home  0.679469  0.041873  0.454750  0.064680       1958.0         0.0
3   pubmed  0.659128  0.050749  0.618574  0.067142       3944.0         0.0
4     tech  0.906599  0.027906  0.838410  0.035368       9486.0         0.0
5  OVERALL  0.573566  0.014070  0.408511  0.010079          NaN         NaN
============================================================
['arxiv', 'cora', 'home', 'pubmed', 'tech']
Test group 0 ['arxiv', 'cora', 'home', 'pubmed', 'tech']
Total params: 16.87552
Trainable params: 16.87552
Non-trainable params: 0.0
2026-08-07 19:43:10.826504: Loaded pretrain_link1
Global Magnitude Pruning: 30.0%
Threshold = 0.00531659
2026-08-07 19:43:31.263141: Epoch 100/100, arxiv Test: Acc_mean = 0.4909, Acc_std = 0.0258, F1_mean = 0.2998, F1_std = 0.0186, tstNum_mean = 48603.0000, tstNum_std = 0.0000
2026-08-07 19:43:33.787609: Epoch 100/100, cora Test: Acc_mean = 0.6151, Acc_std = 0.0049, F1_mean = 0.5592, F1_std = 0.0033, tstNum_mean = 3414.0000, tstNum_std = 0.0000
2026-08-07 19:43:35.283727: Epoch 100/100, home Test: Acc_mean = 0.6282, Acc_std = 0.0540, F1_mean = 0.4025, F1_std = 0.0888, tstNum_mean = 1958.0000, tstNum_std = 0.0000
2026-08-07 19:43:37.361695: Epoch 100/100, pubmed Test: Acc_mean = 0.7382, Acc_std = 0.0327, F1_mean = 0.7129, F1_std = 0.0411, tstNum_mean = 3944.0000, tstNum_std = 0.0000
2026-08-07 19:45:51.608442: Epoch 100/100, tech Test: Acc_mean = 0.8292, Acc_std = 0.1510, F1_mean = 0.6893, F1_std = 0.2412, tstNum_mean = 9486.0000, tstNum_std = 0.0000
2026-08-07 19:45:51.608442: Epoch 100/100, OVERALL Overall Test: Acc_mean = 0.5633, Acc_std = 0.0337, F1_mean = 0.3949, F1_std = 0.0401
   Dataset  Acc_mean   Acc_std   F1_mean    F1_std  tstNum_mean  tstNum_std
0    arxiv  0.490933  0.025829  0.299809  0.018563      48603.0         0.0
1     cora  0.615114  0.004856  0.559240  0.003333       3414.0         0.0
2     home  0.628192  0.053961  0.402532  0.088835       1958.0         0.0
3   pubmed  0.738185  0.032700  0.712891  0.041073       3944.0         0.0
4     tech  0.829201  0.150980  0.689282  0.241201       9486.0         0.0
5  OVERALL  0.563282  0.033707  0.394914  0.040125          NaN         NaN
============================================================